modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Mrbysco/PeanutCraft/issues"

[[mods]]
modId="peanutcraft"
version="${file.jarVersion}"
displayName="PeanutCraft"
displayURL="https://minecraft.curseforge.com/projects/PeanutCraft"
authors="Mrbysco"
description='''
Just a mod about peanuts
'''