modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/Mrbysco/PeanutCraft/issues"
license="MIT"

[[mods]]
modId="peanutcraft"
version="${file.jarVersion}"
displayName="PeanutCraft"
displayURL="https://minecraft.curseforge.com/projects/PeanutCraft"
authors="Mrbysco"
description='''
Just a mod about peanuts
'''
[[dependencies.peanutcraft]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"