modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/PeanutCraft/issues"
license="MIT"

[[mods]]
modId="peanutcraft"
version="${file.jarVersion}"
displayName="PeanutCraft"
displayURL="https://minecraft.curseforge.com/projects/PeanutCraft"
authors="Mrbysco"
description='''
Just a mod about peanuts
'''
[[dependencies.peanutcraft]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.peanutcraft]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.60-beta,)"
ordering="NONE"
side="BOTH"