modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/PeanutCraft/issues"
license="MIT"

[[mods]]
modId="peanutcraft"
version="${file.jarVersion}"
displayName="PeanutCraft"
displayURL="https://www.curseforge.com/minecraft/mc-mods/peanutcraft"
authors="Mrbysco"
description='''
Just a mod about peanuts
'''
[[dependencies.peanutcraft]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.21.5,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.peanutcraft]]
modId="neoforge"
type="required"
versionRange="[21.5.0-beta,)"
ordering="NONE"
side="BOTH"